# Generated by Django 3.0.7 on 2020-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scatter_api', '0002_auto_20200706_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='Questions',
        ),
        migrations.AddField(
            model_name='game',
            name='round_one_questions',
            field=models.ManyToManyField(default=[], related_name='r_one', to='scatter_api.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='round_three_questions',
            field=models.ManyToManyField(default=[], related_name='r_three', to='scatter_api.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='round_two_questions',
            field=models.ManyToManyField(default=[], related_name='r_two', to='scatter_api.Question'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
