# Generated by Django 3.0.7 on 2020-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scatter_api', '0004_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.IntegerField(default=-1),
        ),
    ]
