# Generated by Django 3.0.7 on 2020-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scatter_api', '0005_game_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='submissions',
            field=models.IntegerField(default=0),
        ),
    ]
