# Generated by Django 3.0.7 on 2020-07-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scatter_api', '0006_auto_20200723_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='submissions',
        ),
    ]
